version: '3'
services:
  api:
    build:
      context: ./backend  
    ports:
      - "5000:5000"

  client:
    build:
 
      context: ./frontend 
    ports:
      - "3000:3000"

  nginx:
    build:
     context: ./nginx
    ports:
      - "80:80"
     # - "3000:3000"
     # - "5000:5000"
      

    
