
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /frontend
        backend:
          service:
            name: frontend-clusterip
            port:
              number: 3000
      - pathType: Prefix
        path: /backend
        backend:
          service:
            name: backend-clusterip
            port:
              number: 5000

